name: Sync and Mirror

on: pull_request

jobs:
  sync-mirrors:
    strategy:
      fail-fast: false
      matrix:
        remote:
          - git@bitbucket.org:manifestautoupdate/manifestautoupdate.git
          - git@codeberg.org:electron-shaders/ManifestAutoUpdate.git
          - git@gitea.com:electron-shaders/ManifestAutoUpdate.git
          - git@gitcode.net:weixin_43906714/ManifestAutoUpdate.git
        include:
        - remote: git+ssh://electron-shaders@git.launchpad.net/manifestautoupdate
          username: electron-shaders
        - remote: ssh://electronshaders@git.code.sf.net/p/manifestautoupdate/git
          username: electronshaders
    runs-on: ubuntu-latest
    steps:
    - name: Checkout upstream repo
      uses: actions/checkout@v4
      with:
        repository: heyong5454/ManifestAutoUpdate
        fetch-depth: 0    

    - name: Push to mirror repos
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ matrix.remote }}
        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        ssh_username: ${{ matrix.username && matrix.username || 'git' }}
