name: Sync and Mirror

on: pull_request
jobs:
  sync-mirrors:
    strategy:
      matrix:
        remote:
          - git@bitbucket.org:manifestautoupdate/manifestautoupdate.git
          - git@codeberg.org:electron-shaders/ManifestAutoUpdate.git
          - git@gitea.com:electron-shaders/ManifestAutoUpdate.git
          - git@gitcode.net:weixin_43906714/ManifestAutoUpdate.git
          - ssh://electronshaders@git.code.sf.net/p/manifestautoupdate/git
          - ssh://electron-shaders@git.launchpad.net/manifestautoupdate
          - ssh://rhodecode@code.rhodecode.com:3022/u/electron-shaders/ManifestAutoUpdate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout upstream repo
      uses: actions/checkout@v4
      with:
        repository: heyong5454/ManifestAutoUpdate
        fetch-depth: 0    

    - name: Push to mirror repos
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ matrix.remote }}
        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
